name: Test

on:
  pull_request:
  push:
    branches:
      - master

lobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - users: actions/checkout@v2
      - users: actions/setup-node/@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
